USE QSPIDER;
-- 61. WAQTD 2ND MINIMUM SALARY.
SELECT MIN(SAL) FROM EMP_TABLE
WHERE SAL>(SELECT MIN(SAL) FROM EMP_TABLE );

-- 62. WAQTD 5TH MAXIMUM SAL.
SELECT MAX(SAL) FROM EMP_TABLE
WHERE SAL <(SELECT MAX(SAL) FROM EMP_TABLE 
WHERE SAL<(SELECT MAX(SAL) FROM EMP_TABLE 
WHERE SAL<(SELECT MAX(SAL) FROM EMP_TABLE 
WHERE SAL<(SELECT MAX(SAL) FROM EMP_TABLE ))));

-- 63. WAQTD NAME OF THE EMPLOYEES EARNING 3RD MAXIMUM SALARY.
SELECT ENAME FROM EMP_TABLE 
WHERE SAL=(SELECT MAX(SAL) FROM EMP_TABLE 
WHERE SAL<(SELECT MAX(SAL) FROM EMP_TABLE 
WHERE SAL<(SELECT MAX(SAL) FROM EMP_TABLE )));

-- 64. WAQTD EMPNO OF THE EMPLOYEES EARNING 2RD MAXIMUM SALARY.
SELECT EMPNO FROM EMP_TABLE 
WHERE SAL=( SELECT MAX(SAL) FROM EMP_TABLE 
WHERE SAL<(SELECT MAX(SAL) FROM EMP_TABLE ));

-- 65. WAQTD DEPARTMENT NAME OF AN EMPOYEES GETTING 4TH MAX SAL.
SELECT ENAME FROM EMP_TABLE 
WHERE SAL=( SELECT MAX(SAL) FROM EMP_TABLE 
WHERE SAL<(SELECT MAX(SAL) FROM EMP_TABLE 
WHERE SAL < (SELECT MAX(SAL) FROM EMP_TABLE 
WHERE SAL<(SELECT MAX(SAL) FROM EMP_TABLE ))));


-- 66. WAQTD DETAILS OF THE EMPLOYEES WHO WAS HIRED 2ND.
SELECT * FROM EMP_TABLE 
WHERE HIREDATE=(SELECT MIN(HIREDATE) FROM EMP_TABLE 
WHERE HIREDATE>(SELECT MIN(HIREDATE) FROM EMP_TABLE));

-- 67. WAQTD NAME OF THE EMPLOYEES HIRED BEORE THE LAST EMPLOYEE
SELECT ENAME FROM EMP_TABLE 
WHERE HIREDATE =(SELECT MAX(HIREDATE) FROM EMP_TABLE 
WHERE HIREDATE < (SELECT MAX(HIREDATE) FROM EMP_TABLE));

--  68. WAQTD LOC OF THE EMOLOYEES WHO WAS HIRED FIRST 
SELECT LOC FROM DEPT 
WHERE DEPTNO =( SELECT DEPTNO FROM EMP_TABLE 
WHERE HIREDATE=(SELECT MAX(HIREDATE) FROM EMP_TABLE));

--  69. WAQTD DETAILS OF THE EMPLOYEES EARNING 7TH MINIMUM SALARY 
SELECT MIN(SAL) FROM EMP_TABLE 
WHERE SAL>(
SELECT MIN(SAL) FROM EMP_TABLE 
WHERE SAL>(
SELECT MIN(SAL) FROM EMP_TABLE 
WHERE SAL>(
SELECT MIN(SAL) FROM EMP_TABLE 
WHERE SAL>(
SELECT MIN(SAL) FROM EMP_TABLE 
WHERE SAL>(
SELECT MIN(SAL) FROM EMP_TABLE 
)))));

--  70. WAQTD DNAME OF THE EMPLOYEES GETTING 2ND MAXIMUM SALARY.

SELECT DNAME FROM DEPT 
WHERE DEPTNO IN (SELECT DEPTNO FROM EMP_TABLE 
WHERE SAL IN(SELECT MAX(SAL) FROM EMP_TABLE 
WHERE SAL<(SELECT MAX(SAL) FROM EMP_TABLE)));
