USE QSPIDER;
-- 71. WAQTD SMITHS REPORTING MANAGER'S NAME.
SELECT ENAME FROM EMP_TABLE 
WHERE EMPNO=(SELECT MGR FROM EMP_TABLE WHERE ENAME="SMITH");

-- 72. WAQTD ADAMS MANAGER'S MANAGER NAME.
SELECT ENAME FROM EMP_TABLE 
WHERE EMPNO=(SELECT MGR FROM EMP_TABLE 
WHERE EMPNO=( SELECT MGR FROM EMP_TABLE WHERE ENAME="ADAMS"));


-- 73. WAQTD DNAME OF JONES MANAGER.
SELECT DNAME FROM DEPT 
WHERE DEPTNO=(SELECT DEPTNO FROM EMP_TABLE 
WHERE EMPNO=(SELECT MGR FROM EMP_TABLE WHERE ENAME="JONES"));

-- 74. WAQTD MILLER'S MANAGER'S SALARY
SELECT SAL FROM EMP_TABLE 
WHERE EMPNO=(SELECT MGR FROM EMP_TABLE 
WHERE ENAME="MILLER");

-- 75. WAQTD LOC OF THE SMITH'S MANAGER'S MANAGER.
SELECT LOC FROM DEPT
WHERE DEPTNO=(SELECT DEPTNO FROM EMP_TABLE 
WHERE EMPNO=(SELECT MGR FROM EMP_TABLE 
WHERE EMPNO=(SELECT MGR FROM EMP_TABLE 
WHERE ENAME="SMITH")));

-- 76. WAQTD NAME OF THE EMPLOYEES REPORTING TO BLAKE.
SELECT ENAME FROM EMP_TABLE 
WHERE MGR=(SELECT EMPNO FROM EMP_TABLE 
WHERE ENAME="BLAKE");


-- 77. WAQTD NUMBER OF THE EMPLOYEES REPORTING TO KING;
SELECT COUNT(*) FROM EMP_TABLE 
WHERE MGR = (SELECT EMPNO FROM EMP_TABLE 
WHERE ENAME="KING");


-- 78. WAQTD DETAILS OF THE EMPLOYEES REPORTING TO JONES.
SELECT * FROM EMP_TABLE 
WHERE MGR=(SELECT EMPNO FROM EMP_TABLE 
WHERE ENAME ="JONES");


-- 79. WAQTD ENAMES OF THE EMPLOYEES REPORTING TO BLAKES MANAGER.
SELECT ENAME FROM EMP_TABLE 
WHERE MGR =(SELECT MGR FROM EMP_TABLE 
WHERE ENAME="BLAKE");

-- 80. WAQTD NUMBER OF EMPLOYEES REPORTING TO FORD'S MANAGER.
SELECT COUNT(*) FROM EMP_TABLE 
WHERE MGR =(SELECT MGR FROM EMP_TABLE 
WHERE ENAME="FORD");

SELECT * FROM DEPT;
SELECT * FROM EMP_TABLE;

