SELECT * FROM EMP_TABLE;


-- 1. WAQTD NUMBR OF EMPLOYEES WORKING IN EACH DEPARTMENT EXCEPT PRESIDENT.
SELECT DEPTNO, COUNT(*) FROM EMP_TABLE
WHERE JOB !="PRESIDENT"
GROUP BY DEPTNO;

-- 2. WAQTD TOTAL SALARY NEEDED TO PAY ALL THE EMPLOYEES IN EACH JOB.
SELECT JOB,SUM(SAL) FROM EMP_TABLE
GROUP BY JOB;

-- 3. WAQTD NUMBER OF EMPLOYEES WORKING AS MANAGER IN EACH DEPARTMENT.
SELECT DEPTNO, COUNT(*) FROM EMP_TABLE
WHERE JOB="MANAGER"
GROUP BY DEPTNO;

-- 4. WAQTD AVG SALARY NEEDED TO PAY ALL THE EMPLOYEES IN EACH DEPARTMENET EXCLUDING THE EMPLOYEES OF DEPTNO 20.
SELECT DEPTNO, AVG(SAL) FROM EMP_TABLE
GROUP BY DEPTNO;

-- 5. WAQTD NUMBER OF EMPLOYEES HAVING CHARACTER "A" IN THEIR NAMES IN EACH JOB.
SELECT JOB,COUNT(*) FROM EMP_TABLE
WHERE ENAME LIKE "%A%"
GROUP BY JOB;

-- 6. WAQTD NUMBER OF EMPLOYEES AND AVG SALARY NEEDED TO PAY THE EMPLOYEES WHO SALARY IN GREATER THAN 2000 IN EACH DEPT.
SELECT DEPTNO,COUNT(*), AVG(SAL) FROM EMP_TABLE
WHERE SAL>2000
GROUP BY DEPTNO;

-- 7. WAQTD TOTAL SALARY NEEDED TO APY AND NUMBER OF SALESMAN IN EACH DEPT.
SELECT JOB, DEPTNO ,SUM(SAL) FROM EMP_TABLE
WHERE JOB="SALESMAN"
GROUP BY DEPTNO;

-- 8. WAQTD NUMBER OF EMPLOYEES WITH THEIR MAXIMUM SALARIES IN EACH JOB.
SELECT COUNT(*), MAX(SAL) FROM EMP_TABLE
GROUP BY JOB;

-- 9. WAQTD MAXIMUM SALARIES GIVEN TO AN EMPLOYEES WORKING IN EACH DEPT.
SELECT DEPTNO, MAX(SAL) FROM EMP_TABLE
GROUP BY DEPTNO;

-- 10. WAQTD NUMBER OF TIMES THE SALARIES PRESENT IN EMPLOYEE TABLE.
SELECT COUNT(SAL) FROM EMP_TABLE;


 
