SELECT * FROM EMP_TABLE;

-- 1. WAQTD THE ANNUAL SALARY OF THE EMPLOYEE WHOSE NAME IS SMITH.

SELECT SAL*12 FROM EMP_TABLE
WHERE ENAME="SMITH";

-- 2. WAQTD NAME OF THE EMPLOYEE WORKING AS CLERK.

SELECT ENAME FROM EMP_TABLE
WHERE JOB="CLERK";

-- 3. WAQTD SLARY OF THE EMPLOYEE EARNS MORE THAN 2000.
SELECT ENAME, SAL FROM EMP_TABLE
WHERE SAL>2000;

-- 4. WAQTD DETAILS OF THE  EMPLOYEES WHO ARE WORKING AS SALESMAN.
SELECT * FROM EMP_TABLE
WHERE JOB="SALESMAN";

-- 5. WAQTD DETAILS OF THE  EMP WHO NAME IS JONES.
SELECT * FROM EMP_TAB
WHERE ENAME ="JONES";

-- 6. WAQTD DETAILS OF THE EMP WHO WAS HIRED AFTER 01-JAN-81.
SELECT * FROM EMP_TABLE 
WHERE HIREDATE > "01-JAN-81";

-- 7. WAQTD  NAME AND SAL ALONG WITH HIS ANNUAL SALARY IF THE ANNUAL SALARY IS MORE THAN 1200.
SELECT ENAME,SAL*12 FROM EMP_TABLE
WHERE (SAL*12)>12000;

-- 8. WAQTD EMPNO. OF THE EMPLOYEES WHO ARE WORKING IN DEPT 30.

SELECT EMPNO FROM EMP_TABLE
WHERE DEPTNO=30;

-- 9. WAQTD ENAME AND HIREDDATE IF THEY ARE HIRED BEFORE 1981.
SELECT ENAME,HIREDATE FROM EMP_TABLE
WHERE HIREDATE < "01-JAN-81"; 

-- 10. WAQTD DETAILS OF THE EMPLOYEES WORKING AS MANAGER.
SELECT * FROM EMP_TABLE
WHERE JOB="MANAGER";

-- 11. WAQTD NAME AND SALARY GIVEN TO AN EMPLOYEE IF EMPLOYEE EARNS A COMMISSION OF RUPEES 1400.
SELECT ENAME, SAL FROM EMP_TABLE
WHERE COMM=1400;

-- 12. WAQTD DETAILS OF EMPLOYEES HAVING COMMISSION MORE THAN SALARY.
SELECT * FROM EMP_TABLE
WHERE COMM>SAL;

-- 13. WAQTD EMPNO OF EMPLOYEES HIRED BEFORE THE YEAR 87.
SELECT EMPNO FROM EMP_TABLE
WHERE HIREDATE<"01-JAN-87";

-- 14. WAQTD DETAILS OF THE EMPLOYEES WORKING AS AN ANALYSTS.
SELECT * FROM EMP_TABLE
WHERE JOB="ANALYST";

-- 15. WAQTD DETAILS OF EMPS EARNING MORE THAN 2000 RUPEES PER MONTH.
SELECT * FROM EMP_TABLE
WHERE SAL>2000;
