-- ASSIGNMENT OF SELF JOIN.
-- 1. WAQTD NAME OF THE EMPLIYEES AND HIS MANAGER'S NAME IF EMPLOYEE IS WORKING AS CLERK.
SELECT E1.ENAME, E2.ENAME FROM EMP_TABLE AS E1 JOIN EMP_TABLE AS E2
ON E1.MGR=E2.EMPNO
WHERE E1.JOB='CLERK';

-- 2. WAQTD NAME OF THE  EMPLOYEE AND MANAGER'S DESIGNATION IF MANAGER WORKS IN DEPT 10 OR 20.
SELECT E1.ENAME, E2.JOB FROM EMP_TABLE AS E1 join EMP_TABLE AS E2
ON E1.MGR=E2.EMPNO
WHERE E1.DEPTNO=10 OR  E1.DEPTNO=20;

-- 3. WAQTD NAME OF THE EMP AND MANAGERS SALARY IF EMPLOYEE AND MANAGER BOTH EARN MORE THAN 2300.
SELECT E1.ENAME ,E2.SAL as Manager_salary FROM EMP_TABLE AS E1 JOIN EMP_TABLE AS E2
ON E1.MGR=E2.EMPNO 
WHERE E1.SAL>=2300 AND E2.SAL>=2300;

-- 4. WAQTD EMP NAME AND MANAGER'S HIREDATE IF EMPLOYEE WAS HIRED BEFORE 1982.
SELECT E1.ENAME, E2.HIREDATE FROM EMP_TABLE AS E1 JOIN EMP_TABLE AS E2
ON E1.MGR=E2.EMPNO 
WHERE E1.HIREDATE < "01-JAN-1982";

-- 5. WAQTD EMP NAME AND MANAGER'S COMM IF EMPLOYEE WORKD AS SALESMAN AND MANAGER WORKS IN DEPT 30.
SELECT E1.ENAME,E2.COMM FROM EMP_TABLE AS E1 JOIN EMP_TABLE AS E2
ON E1.MGR=E2.EMPNO 
WHERE E1.JOB="SALESMAN" AND E2.JOB ="MANAGER" ;

-- 6. WAQTD EMP NAME AND MANAGER NAME AND THEIR SALARIES IF EMPLOYEE EARNS MORE THAN MANAGER.
SELECT E1.ENAME, E1.SAL, E2.ENAME AS MG, E2.SAL AS MG_S  FROM EMP_TABLE AS E1 JOIN EMP_TABLE AS E2 
ON E1.MGR=E2.EMPNO
WHERE E1.SAL>E2.SAL; 

-- 7. WAQTD EMP NAME AND HIREDATE, MANAGER NAME AND HIREDATE IF MANAGER WAS HIRED BEFORE EMPLOYEE.
SELECT E1.ENAME AS EMPLOYEE, E1.HIREDATE AS EMPLOYEE_HIREDATE , E2.ENAME AS MANAGER, E2.HIREDATE AS MANAGER_HIREDATE FROM EMP_TABLE AS E1 JOIN EMP_TABLE AS E2
ON E1.MGR=E2.EMPNO
WHERE E2.HIREDATE<E1.HIREDATE;

-- 8. WAQTD EMP NAME AND MANAGER NAME IF BOTH ARE WORKIGN IN SAME JOB.
SELECT E1.ENAME, E2.ENAME FROM EMP_TABLE AS E1 JOIN EMP_TABLE AS E2
ON E1.MGR=E2.EMPNO 
WHERE E1.JOB =E2.JOB;


-- 9. WAQTD EMP NAME AND MANAGER NAME IF MANAGER IS WORKING AS ACTUAL MANAGER.
SELECT E1.ENAME AS EMPLOYEE, E2.ENAME AS MANAGER FROM EMP_TABLE AS E1 JOIN EMP_TABLE AS E2
ON E1.MGR=E2.EMPNO
WHERE E2.JOB="MANAGER";

-- 10. WAQTD EMP NAME AND MANAGER NAME ALONG WITH THEIR ANNUAL SALARIES 
-- IF EMPLOYEE WORKS IN DEPT 10, 20 AND MANAGER'S SAL IS GREATER THAN EMPLOYEES SALARY.
SELECT E1.ENAME AS EMPLOYEE, E1.SAL*12 AS EMPLOYEE_SAL, E2.ENAME AS MANAGER, E2.SAL*12 AS MANAGER_SAL FROM EMP_TABLE AS E1 JOIN EMP_TABLE AS E2
ON E1.MGR=E2.EMPNO 
WHERE E1.DEPTNO IN (10,20) AND E2.SAL>E1.SAL;

-- 11. WAQTD EMPLOYEES NAME AND MANAGER'S DESIGNATION FOR ALL THE EMPLOYEES.
SELECT E1.ENAME, E2.JOB AS MANAGER_JOB FROM EMP_TABLE AS E1 JOIN EMP_TABLE AS E2
ON E1.MGR=E2.EMPNO ;

-- 12. WAQTD EMPLOYEES NAME AND MANAGER'S SALARY FOR ALL THE EMPLOYEES IF MANAGER'S 
-- SALARY ENDS WITH 50.
SELECT E1.ENAME, E2.SAL AS MANAGER_SAL FROM EMP_TABLE AS E1 JOIN EMP_TABLE AS E2
ON E1.MGR=E2.EMPNO 
WHERE E2.SAL LIKE "%50";




