SELECT * FROM EMP_TABLE;

-- 1. WAQTD DETAILS OF THE  EMPLOYEES WORKING AS CLERK AND EARNING LESS THAN 1500.
SELECT * FROM EMP_TABLE
WHERE JOB="CLERK" AND SAL<1500;


-- 2. WAQTD NAME AND HIREDATE OF THE EMPLOYEES WORKING AS MANAGER IN DEPT 30.
SELECT ENAME, HIREDATE FROM EMP_TABLE
WHERE JOB="MANAGER" AND DEPTNO=30;

-- 3.WAQTD DETAILS OF THE EMP ALONG WITH ANNUAL SALARY IF THEY ARE WORKING IN DEPT 30 AS SALESMAN AND THEIR ANNUAL SALARY HAS TO BE GREATER THANN 14000.
SELECT EMP_TABLE.*,SAL*12 FROM 
EMP_TABLE WHERE DEPTNO=30 AND JOB="SALESMAN" AND (SAL*12)>14000;

-- 4. WAQTD ALL THE DETAILS OF THE EMP WORKING IN DEPT 30 OR AS ANALYST.
SELECT * FROM EMP_TABLE
WHERE DEPTNO=30 OR JOB="ANALYST";


-- 5. WAQTD NAMES OF THE EPOLYEES WHOS SALARY IS LESS THAN 1100 AND THEIR DESIGNATION S CLERK.
SELECT ENAME FROM EMP_TABLE
WHERE SAL<1100 AND JOB="CLERK";


-- 6. WAQTD NAME AND SAL, ANNUAL SAL AND DEPTNO IF DEPTNO IS 20 EARNING MORET HAN 1100 AND ANNUAL SALARY EXCEEDS 1200.
SELECT ENAME, SAL, SAL*12, DEPTNO FROM EMP_TABLE
WHERE SAL>1100 AND SAL+12000;

-- 7. WAQTD EMPNO AND NAMES OF THE EMPLOYEES WORKING AS MANAGER IN DEPT 20.

SELECT EMPNO, ENAME FROM EMP_TABLE
WHERE JOB="MANAGER" AND DEPTNO=20;

-- 8. WAQTD DETAILS OF THE  EMPLOYEES WORKING IN DEPT 20 OR 30.
SELECT * FROM EMP_TABLE
WHERE DEPTNO=20 OR DEPTNO=30;

-- 9. WAQTD  DETIALS OF EMPLOYEES WORKING AS ANALYST IN DEPT 10.
SELECT * FROM EMP_TABLE
WHERE JOB="ANALYST" AND DEPTNO=10;

-- 10. WAQTD DETIALS OF EMPLOYEES WORKING AS PRESIDENT WITH SALARY OF RUPEES 4000.
SELECT * FROM EMP_TABLE
WHERE JOB="PRESIDENT" AND SAL=4000;

-- 11. WAQTD NAMES AND DEPTNO. JOB OF EMPS WORKINF AS CLERK IN DEPT 10 OR 20.
SELECT ENAME, DEPTNO , JOB FROM EMP_TABLE
WHERE JOB="CLERK" AND (DEPTNO=10 OR DEPTNO=20);

-- 12. WAQTD DETAILS OF EMPLOYEES WORKING AS CLERK OR MANAGER IN DEPT 10.
SELECT * FROM EMP_TABLE
WHERE JOB="CLERK" OR (JOB="MANAGER" AND DEPTNO=10);

-- 13. WAQTD NAMES OF EMPLOYEES WORKING IN DEPT 10,20,30,40.
SELECT ENAME , DEPTNO FROM EMP_TABLE;

-- 14. WAQTD DETAILS OF EMPLOYEES WITH EMPNO 7902,7839.
SELECT * FROM EMP_TABLE
WHERE EMPNO=7902 OR EMPNO=7839;

-- 15. WAQTD DETAILS OF EMPLOYEES WORKING AS MANAGER OR SALESMAN OR CLERK.
SELECT * FROM EMP_TABLE
WHERE JOB="MANAGER" OR JOB="SALESMAN" OR JOB ="CLERK";

-- 16. WAQTD NAMES OF EMPLOYEES HIRED AFTER 81 AND BEFORE 87.
SELECT ENAME, HIREDATE FROM EMP_TABLE
WHERE HIREDATE>"01-JAN-81" AND HIREDATE<"01-JAN-87";   

-- 17. WAQTD DETIALS OF EMPLOYEES EARNING MORE THAN 1250 BUT LESS THAN 3000.
SELECT * FROM EMP_TABLE
WHERE SAL>1250 AND SAL<3000;

-- 18. WAQTD NAMES OF EMPLOYEES  HIRED AFTER 81 INTO DEPT 10 OR 30.
SELECT ENAME, HIREDATE, DEPTNO FROM EMP_TABLE
WHERE HIREDATE>"01-JAN-81" AND  (DEPTNO=10 OR DEPTNO=30);

-- 19. WAQTD NAMES OF EMPLOYEES ALONG WITH ANNUAL SALARY FOR THE EMPLOYEES WORKING AS MANAGER OR CLERK INTO DEPT 10 OR 30.
SELECT ENAME, SAL*12 AS ANNUAL_SALARY FROM EMP_TABLE
WHERE (JOB="MANAGER" OR JOB="CLERK") AND (DEPTNO=10 OR DEPTNO=30);

-- 20. WAQTD ALL THE  DETAILS ALONG WITH ANNUAL SALARY IF SAL IS BETWEEN 1000 AND 4000 ANNUAL SALARY MORE THAN 15000.
SELECT EMP_TABLE.*, SAL*12 AS ANNUAL_SALARY FROM EMP_TABLE
WHERE (SAL BETWEEN 1000 AND 4000 ) AND (SAL*12 >15000);
