USE QSPIDER;

-- 1. WAQTD NAME OF THE EMPLOYEES EARNING MORE THAN ADAMS;
SELECT ENAME, SAL FROM EMP_TABLE
WHERE SAL>(SELECT SAL FROM EMP_TABLE WHERE ENAME="ADAMS");

-- 2. WAQTD NAME AND SALARY OF THE EMPLOYEES EARNING LESS THAN KING.
SELECT ENAME, SAL FROM EMP_TABLE
WHERE SAL<(SELECT SAL FROM EMP_TABLE WHERE ENAME="KING");

-- 3. WAQTD NAME AND DEPTNO OF THE EMPLOYEES IF THEY ARE WORKING IN THE SAME DEPT AS JONES.
SELECT ENAME , DEPTNO  FROM EMP_TABLE
WHERE DEPTNO =(SELECT DEPTNO FROM EMP_TABLE WHERE ENAME="JONES");

-- 4. WAQTD NAME AND JOB OF ALL THE EMPLOYEES WORKING IN THE SAME DESIGNATION AS JAMES.
SELECT ENAME, JOB  FROM EMP_TABLE
WHERE JOB=(SELECT JOB FROM EMP_TABLE WHERE ENAME="JAMES");

-- 5. WAQTD EMPNO AND ENAME ALONG WITH ANNUAL SALARY OF ALL THE EMPLOYEES IF THEIR ANNUAL SALARY IS GREATER THAN WARDS ANNUAL SALARY.
SELECT EMPNO, ENAME, SAL*12 FROM EMP_TABLE
WHERE SAL*12>(SELECT SAL*12 FROM EMP_TABLE WHERE ENAME="WARD");

-- 6. WAQTD NAME AND HIREDATE OF THE  EMPLOYEES IF THEY ARE HIRED BEFORE SCOTT.

SELECT ENAME, HIREDATE FROM EMP_TABLE
WHERE HIREDATE<(SELECT HIREDATE FROM EMP_TABLE WHERE ENAME="SCOTT");

-- 7. WAQTD NAME AND HIREDATE OF THE EMPLOYEES IF THEY ARE HIRED AFTER THE PRESIDENT.
SELECT ENAME, HIREDATE FROM EMP_TABLE
WHERE HIREDATE>(SELECT HIREDATE FROM EMP_TABLE WHERE JOB="PRESIDENT");

-- 8. WAQTD NAME AND SAL OF THE EMPLOYEES IF THEY ARE EARNING SAL LESS THAN THE EMPLOYEES WHOSE EMPNO IS 7839.
SELECT ENAME, SAL FROM EMP_TABLE 
WHERE SAL < (SELECT SAL FROM EMP_TABLE WHERE EMPNO=7839);

-- 9. WAQTD ALL THE DETAILS OF THE EMPLOYEES IF THE EMPLOYEES ARE HIRED BEFORE MILLER.
SELECT * FROM EMP_TABLE 
WHERE HIREDATE<(SELECT HIREDATE FROM EMP_TABLE WHERE ENAME="MILLER");

-- 10. WAQTD ENAME AND EMPNO OF THE EMPLOYEES IF EMPLOYEES ARE EARNING MORE THAN ALLEN.
SELECT ENAME, EMPNO FROM EMP_TABLE
WHERE SAL>(SELECT SAL FROM EMP_TABLE WHERE ENAME="ALLEN");

-- 11. WAQTD ENAME AND SALARY OF ALL THE EMPLOYEES WHO ARE EARNING MORE THAN MILLER BUT LESS THAN ALLEN.
SELECT ENAME, SAL FROM EMP_TABLE
WHERE (SAL>(SELECT SAL FROM EMP_TABLE WHERE ENAME="MILLER") AND SAL<(SELECT SAL FROM EMP_TABLE WHERE ENAME="ALLEN"));

-- 12. WAQTD ALL THE DETAILS OF THE EMPLOYEES WORKING IN DEPT 20 AND WORKING IN THE SAME DESIGNATION AS SMITH.
SELECT * FROM EMP_TABLE
WHERE (DEPTNO =20 AND JOB =(SELECT JOB FROM EMP_TABLE WHERE ENAME="SMITH"));

-- 13. WAQTD ALL THE  DETAILS OF THE EMPLOYEES WORKING AS MANAGER IN THE SAME DEPT AS TURNER.
SELECT * FROM EMP_TABLE 
WHERE JOB="MANAGER" AND DEPTNO=(SELECT DEPTNO FROM EMP_TABLE WHERE ENAME="TURNER");

-- 14. WAQTD NAME AND HIREDATE OF THE EMPLOYEES HIRED AFTER 1980 AND BEFORE KING.
SELECT ENAME, HIREDATE FROM EMP_TABLE 
WHERE (HIREDATE > "$80" AND HIREDATE < (SELECT HIREDATE FROM EMP_TABLE WHERE ENAME="KING"));


-- 15. WAQTD NAME  AND SAL  ALONG WITH ANNUAL SAL FOR ALL EMPLOYEES WHOSE SAL IS LESS THAN BLAKE AND MORE THAN 3500.

SELECT ENAME, SAL*12 FROM EMP_TABLE 
WHERE (SAL > 3500 AND SAL <(SELECT SAL*12 FROM EMP_TABLE WHERE ENAME ="BLAKE"));

-- 16. WAQTD ALL THE DETAILS OF EMPLOYEES  WHO EARNING WHO EARN MORE THAN SCOTT BUT LESS THA KING.
SELECT * FROM EMP_TABLE 
WHERE (SAL > (SELECT SAL FROM EMP_TABLE WHERE ENAME="SCOTT") AND SAL<(SELECT SAL FROM EMP_TABLE WHERE ENAME="KING"));


-- 17. WAQTD NAME OF THE EMPLOYEES WISE NAME STARTS WITH "A" AND WORKS IN THE SAME DEPT AS BLAKE.
SELECT ENAME FROM EMP_TABLE
WHERE  (ENAME LIKE "A%" AND DEPTNO=(SELECT DEPTNO FROM EMP_TABLE WHERE ENAME ="BLAKE"));

-- 18. WAQTD NAME AND COMM IF EMPLOYEES EARN COMISSION AND WORK IN THE SAME DESIGNATION AS SMITH.
SELECT ENAME, COMM FROM EMP_TABLE 
WHERE (COMM IS NOT NULL  AND JOB=(SELECT JOB FROM EMP_TABLE WHERE ENAME ="SMITH"));


-- 19. WAQTD DETAILS OF ALL THE EMPLOYEES WORKING AS CLERK IN THE  SAME DEPT AS TURNER.
SELECT * FROM EMP_TABLE 
WHERE (JOB="CLERK" AND DEPTNO=(SELECT DEPTNO FROM EMP_TABLE WHERE ENAME="TURNER"));

-- 20. WAQTD ENAME, SAL AND DESIGNATION OF THE EMPLOYEES WHOSE ANNUAL SALARY IS MORE THAN SMITH AND LESS THAN KING.

SELECT ENAME, SAL,JOB FROM EMP_TABLE
WHERE (SAL*12>(SELECT SAL*12 FROM EMP_TABLE WHERE ENAME ="SMITH") AND SAL*12<(SELECT SAL*12 FROM EMP_TABLE WHERE ENAME="KING"));

