USE QSPIDER;

-- 41. WAQTD NAME OF THE EMPLOYEES EARNING MAXIMUM SALARY.
SELECT ENAME FROM EMP_TABLE
WHERE SAL=(SELECT MAX(SAL) FROM EMP_TABLE);

-- 42. WAQTD NAME OF THE EMPLOYEES EARNING MINIMUM.
SELECT ENAME FROM EMP_TABLE
WHERE SAL IN (SELECT MIN(SAL) FROM EMP_TABLE);

-- 43. WAQTD NAME AND HIREDAATE OF THE EAMPLOYEES HIRED BEFORE ALL THE EMPLOYEES (FIRST EMP)
SELECT ENAME, HIREDATE FROM EMP_TABLE
WHERE HIREDATE < (SELECT MIN(HIREDATE) FROM EMP_TABLE);

-- 44. WAQTD NAME AND HIREDATE OF THE EMPLOYEES AT THE LAST.
SELECT ENAME, HIREDATE FROM EMP_TABLE
WHERE HIREDATE = (SELECT MAX(HIREDATE) FROM EMP_TABLE);

-- 45. WAQTD NAME, COMM OF THE EMPLOYEE WHO EARNS MIN COMISSION.
SELECT ENAME, COMM FROM EMP_TABLE
WHERE COMM =(SELECT MIN(COMM) FROM EMP_TABLE);

-- 46. WAQTD NAME, SAL AND COMM OF THE EMPLOYEES EARNING MAXIMUM COMMISSION.
SELECT ENAME, SAL, COMM FROM EMP_TABLE
WHERE COMM = (SELECT MAX(COMM) FROM EMP_TABLE);


-- 47. WAQTD DETAILS OF THE EMPLOYEES WHO HAS GREATEST EMPNO.
SELECT * FROM EMP_TABLE 
WHERE EMPNO=(SELECT MAX(EMPNO) FROM EMP_TABLE);

 -- 48. WAQTD DETAILS OF THE EMPLOYEES HAVING THE LEAST HIREDATE.
 SELECT * FROM EMP_TABLE 
 WHERE HIREDATE = ( SELECT MIN(HIREDATE) FROM EMP_TABLE );
 
 
 -- 49. WAQTD DETAILS OF THE EMPLOYEES EARNING LEAST ANNUAL SALARY.
SELECT * FROM EMP_TABLE
WHERE SAL*12 =(SELECT MIN(SAL*12) FROM EMP_TABLE);


-- 50. WAQTD NAME, ANNUAL SALARY OF THE EMPLOYEES IF THEIR ANNUAL SALARY IS MORE THAN ALL THE SALESMAN.
 SELECT ENAME, SAL*12 FROM EMP_TABLE
 WHERE SAL*12 > ( SELECT MAX(SAL*12) FROM EMP_TABLE WHERE JOB="SALESMAN");
 
 
 