-- QUESTIONS 
SELECT
    *
FROM
    EMP_TABLE;

-- 1. WAQTD NAME OF THE EMPLOYEE ALONG WITH THEIR  ANNUAL SALARY.
SELECT
    ENAME, SAL * 12 AS ANNUAL_SALARY
FROM
    EMP_TABLE;

-- 2. WAQTD ENAME AND JOB FOR ALL THE EMPOLYEE WITH THEIR  HALF TERM SALARY.
SELECT 
    ENAME, SAL * 6 AS HALF_TERM_SALARY
FROM
    EMP_TABLE;

-- 3. WAQTD ALL THE DETAILS OF THE EMPLOYEES ALONG WITH ANNUALBOUNUS OF 2000.
SELECT 
    EMP_TABLE.*, SAL * 12 + 2000 AS ANNUAL_BONUS_OF_2000
FROM
    EMP_TABLE;

-- 4. WAQTD NAME SALARY AND SALARY WITH A HIKE OD 10%.
SELECT 
    ENAME, SAL, ROUND(SAL + SAL * 10 / 100, 0) AS SALARY_HIKE
FROM
    EMP_TABLE;

-- 5. WAQTD NAME SALARY AND SALARY WITH DEDUCTION OF 25%.
SELECT 
    ENAME, SAL, ROUND(SAL - SAL * 25 / 100, 0) AS DEDUCTION
FROM
    EMP_TABLE;

-- 6. WAQTD NAME ANS SALARY WITH MONTHLY HIKE OF 50.
SELECT 
    ENAME, (SAL + 50) * 12 AS MONTHLY_HIKE
FROM
    EMP_TABLE;

-- 7. WAQTD NAME AND ANNUAL_SALARY WITH DEDUCTION OF 10%.
SELECT 
    ENAME,
    ROUND((SAL * 12) - (SAL * 12) * 10 / 100, 0) AS ANNUAL_SALARY_DEDUCTION
FROM
    EMP_TABLE;

-- 8. WAQTD TOTAL SALARY GIVEN TO EACH EMPLOYEE (SAL+COM).
SELECT 
    ENAME, SAL + COMM AS TOTAL_SALARY
FROM
    EMP_TABLE;

-- 9. WAQTD DETAILS OF ALL THE EMPLOYEES ALONG WITH ANNUAL SALARY.
SELECT 
    EMP_TABLE.*, (SAL + COMM) * 12 AS ANNUAL_SALARY
FROM
    EMP_TABLE;

-- 10. WAQTD NAME AND DESIGNATION ALONG WITH 100 PENALTY IN SALARY.

SELECT 
    ENAME, JOB, (SAL + COMM) - 100 PENALTY
FROM
    EMP_TABLE;



