
USE QSPIDER;
SELECT * FROM EMP_TABLE;

-- 1. WAQTD DNO AND NUMBER OF EMP WORKING IN EACH DEPT IF THERE ARE ATLEAST 2 CLERK IN EACH DEPT.
SELECT DEPTNO, COUNT(*) FROM EMP_TABLE
WHERE JOB="CLERK"
GROUP BY DEPTNO
HAVING COUNT(*)>=2;

-- 2.  WAQTD DNO AND TOTAL SALARY NEEDED TO PAY ALL EMP IN EACH DEPT IF THERE ARE AT LEAST 4 EMP IN EACH DEPT.
SELECT DEPTNO, SUM(SAL) FROM EMP_TABLE
GROUP BY DEPTNO
HAVING COUNT(*)>=4;

-- 3. WAQTD NUMBER OF EMP EARNING SAL MORE THAN 1200 IN EACH JOB AND
--  THE TOTAL SALARY NEEDED TO PAY EMP IN EACH JOB MUST EXCEES 3800.
SELECT COUNT(*),JOB,SUM(SAL)  FROM EMP_TABLE
WHERE SAL>1200 
GROUP BY JOB
HAVING SUM(SAL)>3800;


-- 4. WAQTD DEPTNO AND NUMBER OF EMP WORKING ONLY IF THEIR 
-- ARE 2 EMP WORKING IN EACH DEPT AS MANAGER.

SELECT DEPTNO, COUNT(*) FROM EMP_TABLE
WHERE JOB="MANAGER"
GROUP BY DEPTNO 
HAVING COUNT(*)=2;

-- 5. WAQTD JOB AND MAX SAL OF EP IN EACH IF THE MAX SAL EXCEEDS 2600.
SELECT JOB, MAX(SAL) FROM EMP_TABLE
GROUP BY JOB 
HAVING MAX(SAL)>2600;

-- 6. WAQTD THE SALARIES WHICH ARE REPEATED IN EMP TABLE.
SELECT SAL,COUNT(*) FROM EMP_TABLE
GROUP BY SAL
HAVING COUNT(*)>=2;


-- 7. WAQTD THE HIREDATE WHICH DUPLICATE IN TABLE.
SELECT HIREDATE, COUNT(*) FROM EMP_TABLE
GROUP BY HIREDATE
HAVING COUNT(*)>=2;


-- 8. WAQTD AVG SALARY OF EACH DEPT IF AVG SAL IS LESS THAN 1000.
SELECT AVG(SAL) FROM EMP_TABLE
GROUP BY DEPTNO
HAVING AVG(SAL)<1000;


-- 9. WAQTD DEPTNO IF THERE ARE ATLEAST 3 EMP IN EACH DEPT WHOSE NAME HAS CHAR 'A' OR 'S'.

SELECT DEPTNO, COUNT(*) FROM EMP_TABLE
WHERE (ENAME LIKE "%A%" OR ENAME LIKE "%S%")
GROUP BY DEPTNO
HAVING COUNT(*)>=3;


-- 10. WAQTD MIN AND MAX SALARIES OF EACH JOB IF MIN SAL IS MORE THAN 1000
-- AND MAX SAL IS LESS THAN 5000.
SELECT JOB, MIN(SAL), MAX(SAL) FROM EMP_TABLE
GROUP BY JOB
HAVING (MIN(SAL)>1000 AND MAX(SAL)<5000);



