use qspider;

-- ASSIGNMENT OF INNER JOINS.
-- 1. NAME OF THE EMPLOYEE AND HIS LOCATION OF ALL EMPLOYEES.
SELECT ENAME, LOC 
FROM EMP_TABLE INNER JOIN DEPT 
ON EMP_TABLE.DEPTNO=DEPT.DEPTNO;

-- 2. WAQTD ENAME AND SALARY FOR ALL THE EMPLOYEE WORKING IN ACCOUNTING.
SELECT ENAME, SAL 
FROM EMP_TABLE INNER JOIN DEPT 
ON EMP_TABLE.DEPTNO=DEPT.DEPTNO 
WHERE DNAME="ACCOUNTING";

-- 3. WAQTD ENAME AND ANNUAL SALARY FOR ALL PLOYEES WHOSE SALARY IS MORE THAN 2340.
SELECT ENAME, SAL*12 FROM EMP_TABLE INNER JOIN DEPT 
ON EMP_TABLE.DEPTNO=DEPT.DEPTNO
WHERE SAL*12 >2340;

-- 4. WAQTD ENAME AND DNAME FOR EMPLOYEES HAVING CHARACTER 'A' IN THEIR DNAME.
SELECT ENAME, DNAME FROM EMP_TABLE INNER JOIN DEPT 
ON EMP_TABLE.DEPTNO=DEPT.DEPTNO
WHERE DNAME LIKE "%A%";

-- 5. WAQTD ENAME AND DNAME FOR ALL THE EMPLOYEES WORKING AS SALESMAN.
SELECT ENAME, DNAME FROM EMP_TABLE INNER JOIN DEPT 
ON EMP_TABLE.DEPTNO = DEPT.DEPTNO 
WHERE JOB="SALESMAN";

-- 6. WAQTD DNAME AND JOB FOR ALL THE ENOLOYEES WHOSE JOB AND DNAME STARTS WITH CHARACTER 'S'.
SELECT DNAME, JOB FROM EMP_TABLE INNER JOIN DEPT
ON EMP_TABLE.DEPTNO =DEPT.DEPTNO 
WHERE (JOB LIKE "S%" AND DNAME LIKE "S%");

-- 7. WAQTD DNAME AND MGR NO. FOR EMPLOYEES REPORTING TO 7839.
SELECT DNAME, MGR FROM EMP_TABLE INNER JOIN DEPT 
ON EMP_TABLE.DEPTNO=DEPT.DEPTNO
WHERE EMPNO IN (SELECT EMPNO FROM EMP_TABLE WHERE MGR=7839);

-- 8. WAQTD DNAME AND HIREDATE FOR EMPLOYEES HIRED AFTER 83 INTO ACCOUNTING OR RESEARCH DEPT.
SELECT DNAME, HIREDATE FROM EMP_TABLE INNER JOIN DEPT
ON EMP_TABLE.DEPTNO=DEPT.DEPTNO
WHERE HIREDATE>"%83" AND (DNAME ="ACCOUNTING" OR DNAME="RESEARCH"); 


-- 9. WAQTD ENAME AND DNAME OF THE EMPLOYEES WHO ARE GETTING COMM IN DEPT 10 OR 30.
SELECT ENAME, DNAME FROM EMP_TABLE INNER JOIN DEPT
ON EMP_TABLE.DEPTNO=DEPT.DEPTNO
WHERE (COMM!=0 AND DEPTNO=10) OR (COMM!=0 AND DEPTNO =30);


-- 10. WAQTD DNAME AND EMPNO FOR ALL THE EMPLOYEES WHOSE EMPNO ARE 7839,7902 AND ARE WORKING IN LOC NEW YORK.
SELECT DNAME, EMPNO FROM EMP_TABLE INNER JOIN DEPT 
ON EMP_TABLE.DEPTNO=DEPT.DEPTNO 
WHERE( EMPNO=7839 OR EMPNO=7902) AND LOC="NEW-YORK";

SELECT * FROM EMP_TABLE;
SELECT * FROM DEPT;



 




