USE QSPIDER;

-- 51.WAQTD NAME OF THE EMPLOYEES EARNING SALARY MORE THAN THE SALESMAN.
SELECT ENAME FROM EMP_TABLE
WHERE SAL > ALL (SELECT SAL FROM EMP_TABLE WHERE JOB="SALESMAN");

-- 52. WAQTD DETAILS OF THE EMPLOYEES HIRED AFTER ALL THE CLERK.
SELECT * FROM EMP_TABLE 
WHERE HIREDATE > ALL (SELECT HIREDATE FROM EMP_TABLE WHERE JOB="CLERK");


-- 53. WAQTD NAME AND SALARY FOR ALL THE EMPLOYEES 
-- IF THEY ARE EARNING LESS THAN ATLEAST A MANAGER.
SELECT ENAME, SAL FROM EMP_TABLE 
WHERE SAL < ANY (SELECT SAL FROM EMP_TABLE WHERE JOB="MANAGER");

-- 54. WAQTD NAME AND HIREDATE OF THE EMPLOYEES HIRED BEFORE ALL THE MANAGERS.
SELECT ENAME, HIREDATE FROM EMP_TABLE 
WHERE HIREDATE < ALL(SELECT HIREDATE FROM EMP_TABLE WHERE JOB="MANAGER");

-- 55. WAQTD NAME OF THE EMPLOYEES HIRED AFTER ALL 
-- THE MANAGERS AND EARNING SALARY MORE THAN ALL THE CLERKS.

SELECT ENAME FROM EMP_TABLE 
WHERE (HIREDATE > ALL ( SELECT HIREDATE FROM EMP_TABLE WHERE JOB="MANAGERS")) AND 
(SAL > ALL (SELECT SAL FROM EMP_TABLE WHERE JOB="CLERK"));

-- 56. WAQTD DETAILS OF THE EMPLOYEES WORKING AS CLERK AND HIRED BEFORE ATLEAST A SALESMAN. 
SELECT * FROM EMP_TABLE 
WHERE JOB="CLERK" AND HIREDATE < ANY (SELECT HIREDATE FROM EMP_TABLE WHERE JOB="SALESMAN");

-- 57. WAQTD DETAILS OF EMPLOYEES WORKING IN ACCOUNTING OR SALES DEPT.
SELECT *  FROM EMP_TABLE 
WHERE DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE (DNAME="ACCOUNTING" OR DNAME ="SALES")) ;

-- 58. WAQTD DEPARTMENT NAMES IF THE EMPLOYEES WITH NAME  SMITH, KING AND MILLER.
SELECT DNAME FROM DEPT 
WHERE DEPTNO IN (SELECT DEPTNO FROM EMP_TABLE WHERE ENAME="SMITH" OR ENAME="KING" OR ENAME="MILLER");

-- 59.WAQTD DETAILS OF EMPLOYEES WORKING NEW YORK OR CHICAGO.
SELECT * FROM EMP_TABLE 
WHERE DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE LOC="NEW-YORK" OR LOC="CHICAGO");

-- 60. WAQTD EMP NAMES IF EMPLOYEES ARE HIRED AFTER ALL THE EMPLOYEES OF DEPT 10.
SELECT ENAME FROM EMP_TABLE 
WHERE HIREDATE < ALL (SELECT HIREDATE FROM EMP_TABLE WHERE DEPTNO=10);











