use qspider;

DESCRIBE EMP_TABLE;
SELECT * FROM EMP_TABLE;

-- 1. LIST ALL THE EMPLOYEES WHOSE COMMISSION IS NULL. /////////
SELECT * FROM EMP_TABLE
WHERE COMM IS NULL;


-- 2. LIST ALL THE EMPLOYEES WHO DON'T HAVE A REPORTING MANAGER.
SELECT * FROM EMP_TABLE
WHERE MGR =0;

-- 3. LIST ALL THE SALESMAN IN DEPT 30 .

SELECT JOB,DEPTNO FROM EMP_TABLE
WHERE (DEPTNO = 30 AND JOB="SALESMAN");

-- 4.  LIST ALL THE SALESMAN IN DEPT NUMBER 30 AND HAVING SALARY GREATER THAN 1500.
SELECT JOB, DEPTNO,SAL FROM EMP_TABLE
WHERE JOB="SALESMAN" AND (DEPTNO=30 AND SAL>1500);

-- 5. LIST ALL THE EMPLOYEES EHOSE NAMES START WITH 'S' OR 'A'.
SELECT * FROM EMP_TABLE
WHERE ENAME LIKE "S%" OR ENAME LIKE "A%" ;

-- 6. LIST ALL THE EMPLOYEES EXCEPT THOSE WHO ARE WORKING IN DEPT 10 & 20.
SELECT * FROM EMP_TABLE
WHERE DEPTNO!=10 AND DEPTNO!=20;

-- 7. LIST THE  EMPLOYEES WHOSE NAME DOES NOT START WITH "S".
SELECT * FROM EMP_TABLE
WHERE ENAME NOT LIKE "S%";

-- 8. LIST ALL THE EMPLOYEES WHO ARE HAVING REPORTING MANAGERS IN DEPT 10.
SELECT * FROM EMP_TABLE
WHERE (MGR !="_%" AND DEPTNO=10);

-- 9. LIST ALL THE EMPLOYEES WHOSE COMMISSION IS NULL AND WORKING AS CLERK. 
SELECT  * FROM EMP_TABLE
WHERE (COMM = 0 AND JOB="CLERK");

-- 10. LIST ALL THE  EMPLOYEES WHO DON'T HAVE A REPORTING MANAGER IN DEPTNO. 10 OR 30.
SELECT * FROM EMP_TABLE
WHERE MGR=" " AND (DEPTNO=10 OR DEPTNO=30);

-- 11. LIST ALL THE SALESMEN IN DEPT 30 WITH SAL MORE THAN 2450.

SELECT * FROM EMP_TABLE
WHERE JOB="SALESMAN" AND (DEPTNO=30 AND SAL>2450);

-- 12. LIST ALL THE ANALYST IN DEPT NUMBER 20 AND HAVING SALARY GREATER THAN 2500.
SELECT * FROM  EMP_TABLE
WHERE JOB="ANALYST" AND (DEPTNO=20 AND SAL>2500);

-- 13. LIST ALL THE EMPLOYEES WHOSE NAMES STARTS WITH "M" OR "J";
SELECT * FROM EMP_TABLE
WHERE ENAME LIKE "M%" OR ENAME LIKE "J%";

-- 14. LIST ALL THE EMPLOYEES WITH ANNUAL SALARY EXCEPT THOSE WHO ARE WORKING IN DEPT 30.
SELECT EMP_TABLE.*, SAL*12 AS ANNUAL_SALARY FROM EMP_TABLE
WHERE DEPTNO !=30 ;

-- 15. LIST THE EMPLOYEES WHOSE  NAME DOES NOT END WITH "ES" OR "R".
SELECT * FROM EMP_TABLE
WHERE ENAME NOT LIKE "%ES" OR ENAME NOT LIKE "%R";

-- 16. LIST ALL THE EMPLOYEES WHO ARE HAVING REPORTING MANAGERS IN DEPT 10 ALONG WITH 10% HIKE IN SALARY.

SELECT *, SAL+SAL*10/100 AS HIKE FROM EMP_TABLE
WHERE MGR!=0 AND (DEPTNO=10 AND SAL+SAL*10/100>SAL);

-- 17. DISPLAY ALL THE EMPLOYEES WHO  ARE SALESMAN HAVING "E" AS THE LAST BUT ONE CHARACTER IN ENAME BUT SALARY HAVING EXACTLY 4 CHARACTER.
SELECT * FROM EMP_TABLE
WHERE JOB="SALESMAN" AND (ENAME LIKE "%E_"  AND SAL LIKE "____");
 
-- 18. DISPLAY ALL THE EMPLOYEE WHO ARE  JOINED AFTER YEAR 81.
SELECT * FROM EMP_TABLE
WHERE HIREDATE >="30-DEC-81";

-- 19. DISPLAY ALL THE EMPLOYEES WHO ARE JOINED IN FEB;
SELECT * FROM EMP_TABLE
WHERE HIREDATE=DATE(HIREDATE,"MM");

--  20. LIST THE EMPLOYEES WHO ARE NOT WORKING AS MANAGERS AND CLERKS IN DEPT 
-- 10 AND 20 WITH A SALARY IN THE RANGE OF 1000 TO 3000.
SELECT 
    *
FROM
    EMP_TABLE
WHERE
    (JOB NOT IN ('MANAGER')
        AND (JOB NOT IN ('CLERK')
        AND (DEPTNO NOT IN (10 , 20) AND SAL < 3000
        AND SAL > 1000)));






