SELECT * FROM EMP_TABLE;

-- 1. WAQTD NUMBER OF EMPLOYEES GETTING SALARY LESS THAN 2000 IN DEPTNO 10.
SELECT COUNT(*) FROM EMP_TABLE
WHERE (SAL<2000 AND DEPTNO=10);

-- 2. WAQTD TOTAL SALARY NEEDED TO PAY EMPLOYEES WORKING AS CLERK.
SELECT SUM(SAL) FROM EMP_TABLE
WHERE JOB="CLERK";

-- 3. WAQTD AVERAGE SALARY NEEDED  TO PAY ALL EMPLOYEES.
SELECT AVG(SAL) AS AVERAGE_SALARY FROM EMP_TABLE;

-- 4. WAQTD NUMBER OF EMPLOYEES HAVING AS CLERK OR MANAGER.
SELECT COUNT(*) AS NO_OF_EMPLOYEES FROM EMP_TABLE
WHERE JOB IN ("CLERK", "MANAGER");

-- 5. WAQTD NUMBER OF EMPLOYEES HAVING "A" AS THEIR FIRST CHARACTER.
SELECT ENAME FROM EMP_TABLE
WHERE ENAME LIKE "A%";

-- 6. WAQTD TOTAL SALARY NEEDED TO PAY EMOPLOYEES HIRED IN FEB.
SELECT SUM(SAL) FROM EMP_TABLE
WHERE HIREDATE LIKE "%-FEB-%";

-- 7. WAQTD NUMBER OF EMPLOYEES REPORTING TO 7839 (MGR).
SELECT COUNT(*) FROM EMP_TABLE
WHERE MGR=7839;

-- 8. WAQTD NUMBER OF EMPLOYEES GETTING COMISSION IN DEPTNO. 30.
SELECT COUNT(*) FROM EMP_TABLE
WHERE (COMM IS NOT NULL AND DEPTNO=30);

-- 9. WAQTD AVG SAL, TOTAL SAL, NUMBER OF EMPS AND MAXIMUM SALARY GIVEN TO EMPLOYEES WORKING AS PERSIDENT.
SELECT AVG(SAL),SUM(SAL),COUNT(*) AND MAX(SAL) FROM EMP_TABLE
WHERE JOB="PRESIDENT";

-- 10. WAQTD NUMEBR OF EMPLOYEES HAVING "A" IN THEIR NAMES.
SELECT COUNT(*) FROM EMP_TABLE
WHERE ENAME LIKE "A%";

-- 11. WAQTD NUMBER OF EMPLOYEES AND TOTAL SALARY NEEDED TO PAY THE EMPLOYEES WHO HAAVE 2 CONSTRUCTIVE L'S IN THEIR NAMES.
SELECT COUNT(*), SUM(SAL) FROM EMP_TABLE
WHERE ENAME LIKE "%LL%";

-- 12. WAQTD NUMBER OF DEPARTMENT PRESENT IN EMPLOYEE TABLE.
SELECT COUNT(DEPTNO) FROM EMP_TABLE;

-- 13. WAQTD NUMBER OF EMPLOYEES HAVING 'S' IN THEIR NAMES.
SELECT COUNT(ENAME) FROM EMP_TABLE
WHERE ENAME LIKE "S%"; 

-- 14. WAQTD NUMBER OF EMPLOYEES HAVING CHARACTER 'Z' IN THEIR NAMES.
SELECT COUNT(*) FROM EMP_TABLE
WHERE ENAME LIKE "%Z%";


-- 15. WAQTD TOTAL SALARY GIVEN TO EMPLOYEES WORKING AS CLERK IN DEPT 30.
SELECT SUM(SAL) FROM EMP_TABLE
WHERE (JOB="CLERK" AND DEPTNO=30);

-- 16. WAQTD MAXIMUM SALARY GIVEN TO THE EMPLOYEES WORKING AS ANALYST.
SELECT MAX(SAL) FROM EMP_TABLE
WHERE JOB="ANALYST";

-- 17. WAQTD NUMBER OF DISTINCT SALARIES PRESENT IN EMPLOYEE TABLE.
SELECT COUNT(DISTINCT(SAL)) FROM EMP_TABLE;

-- 18. WAQTD NUMBER OFF JOBS PRESENT IN EMPLOYEES TABLE.
SELECT COUNT(DISTINCT(JOB)) FROM EMP_TABLE;

-- 19. WAQTD AVG SALARY GIVEN TO THE  CLERK.
SELECT AVG(SAL) FROM EMP_TABLE
WHERE JOB="CLERK";

-- 20. WAQTD MINIMUM SALARY GIVEN TO THE EMPLOYEES WHO IN DEPT 10 AS MANAGER OR A CLERK.
SELECT MIN(SAL) FROM EMP_TABLE
WHERE (DEPTNO=10 AND JOB="MANAGER") OR JOB="CLERK";


