USE QSPIDER;


CREATE TABLE DEPT (
DEPTNO INT ,
DNAME VARCHAR(30),
LOC VARCHAR(30)
);

INSERT INTO DEPT (DEPTNO, DNAME,LOC)
VALUES 
(10,"ACCOUNTING","NEW-YORK"),
(20,"RESEARCHING","DALLAS"),
(30,"SALES","CHICAGO"),
(40,"OPERATIONS","BOSTON");


-- 21. WAQTD DNAME OF THE EMPLOYEES WHOSE  NAME IS SMITH.

SELECT DNAME FROM DEPT
WHERE DEPTNO= (SELECT DEPTNO FROM EMP_TABLE WHERE ENAME="SMITH");

-- 22. WAQTD DNAME AND LOC OF THE EMPLOYEES WHOSE ENAME IS KING.
SELECT DNAME, LOC FROM DEPT 
WHERE DEPTNO=(SELECT DEPTNO FROM EMP_TABLE WHERE ENAME ="KING");

-- 23. WAQTD LOC OF THE EMP WHOSE EMPLOYEES NUMBER IS 7902.
SELECT LOC FROM DEPT
WHERE DEPTNO=(SELECT DEPTNO FROM EMP_TABLE WHERE EMPNO=7902);

-- 24. WAQTD DNAME AND LOC ALONG WITH DEPTNO OF THE EMPLOYEE WHOSE NAME ENDS WITH "R".
SELECT DNAME, LOC FROM DEPT
WHERE  DEPTNO=(SELECT DEPTNO FROM EMP_TABLE WHERE ENAME LIKE "%R");

-- 25. WAQTD DNAME OF THE EMPLOYEE WHOSE DESIGNATION IS PRESIDENT.
SELECT DNAME FROM DEPT
WHERE DEPTNO=(SELECT DEPTNO FROM EMP_TABLE WHERE JOB ="PRESIDENT");

-- 26. WAQTD NAMES OF THE EMPLOYEES WORKING IN ACCOUNTING DEPARTMENT.
SELECT ENAME FROM EMP_TABLE 
WHERE DEPTNO=(SELECT DEPTNO FROM DEPT WHERE DNAME="ACCOUNTING");

-- 27. WAQTD ENAME AND SALARIES OF THE  EMPLOYEES WHOSE ARE WORKING IN THE LOCATION CHICAGO.
SELECT ENAME, SAL FROM EMP_TABLE
WHERE DEPTNO=(SELECT DEPTNO FROM DEPT WHERE LOC="CHICAGO");

-- 28. WAQTD DETAILS OF THE EMPLOYEES WORKIGN IN SALES.
SELECT * FROM EMP_TABLE 
WHERE DEPTNO=(SELECT DEPTNO FROM DEPT WHERE DNAME="SALES");

-- 29. WAQTD DETAILS OF THE EMP ALONG WITH ANNUAL SALARY IF EMPLOYEES ARE WORKING IN NEW YORK.
SELECT EMP_TABLE.*,  SAL*12 FROM EMP_TABLE
WHERE DEPTNO=(SELECT DEPTNO FROM DEPT WHERE LOC="NEW-YORK");

-- 30. WAQTD NAMES OF THE  EMPLOYEES WORKING IN OPERATIONS DEPARTMENT.
SELECT ENAME FROM EMP_TABLE 
WHERE DEPTNO=(SELECT DEPTNO FROM DEPT WHERE DNAME="OPERATIONS");


-- 31. WAQTD NAMES OF THE EMPLOYEES EARNING MORE THAN SCOTT IN ACCOUTING DEPT.
SELECT ENAME FROM EMP_TABLE 
WHERE (SAL> (SELECT SAL FROM EMP_TABLE WHERE ENAME="SCOTT")) AND DEPTNO =(SELECT DEPTNO FROM DEPT WHERE DNAME="ACCOUNTING");

-- 32. WAQTD DETAILS OF THE EMPLOYEES WORKING AS MANAGER IN THE LOCATION CHICAGO.
SELECT * FROM EMP_TABLE 
WHERE JOB="MANAGER" AND DEPTNO=(SELECT DEPTNO FROM DEPT WHERE LOC="CHICAGO");

-- 33. WAQTD NAME AND SAL OF THE EMPLOYEES EARNING MORE THAN KING IN THE DEPT ACCOUNTING.
SELECT ENAME, SAL FROM EMP_TABLE
WHERE (SAL >(SELECT SAL FROM EMP_TABLE WHERE ENAME ="KING")) AND DEPTNO=(SELECT DEPTNO FROM DEPT WHERE DNAME="ACCOUNTING");

-- 34. WAQTD DETAILS OF THE  ENPLOYEES WOKRKING AS SALESMAN IN THE DEPARTMENT SALES. 

SELECT * FROM EMP_TABLE 
WHERE JOB="SALESMAN" AND DEPTNO=(SELECT DEPTNO FROM DEPT WHERE DNAME="SALES");

-- 35. WAQTD NAME,SAL, JOB, HIREDATE OF THE EMPLOYEES WORKING IN OPERATIONS DEPARTMENT AND HIRED BEFORE KING.

SELECT ENAME, SAL, JOB, HIREDATE FROM EMP_TABLE 
WHERE (HIREDATE<(SELECT HIREDATE FROM EMP_TABLE WHERE ENAME="KING")) AND DEPTNO=(SELECT DEPTNO FROM DEPT WHERE DNAME ="OPERATIONS");

-- 36. DISPLAY ALL THE EMPLOYEES WHOSE DEPARTMENT NAMES ENDING "S".
SELECT * FROM EMP_TABLE 
WHERE DEPTNO=(SELECT DEPTNO FROM DEPT WHERE DNAME LIKE "%S");

-- 37. WAQTD DNAME OF THE EMPLOYEES WHOSE NAME HAS CHARACTER "A" IN IT.
SELECT DNAME FROM DEPT 
WHERE DEPTNO=(SELECT DISTINCT(DEPTNO) FROM EMP_TABLE WHERE ENAME LIKE "%A%");


SELECT DISTINCT(DEPTNO) FROM EMP_TABLE WHERE ENAME LIKE "%A%";



SELECT * FROM DEPT;
SELECT * FROM EMP_TABLE;

