-- PRACTICE ALL THE QUERIES.
USE QSPIDER;

-- I WANT TO PRINT IF SALARY IS MORE THAN 1250 THEN PRINT "HIGHER SALARY" OTHERWISE PRINT "LOW SALARY".

SELECT ENAME, SAL,
CASE 
WHEN SAL>3000 THEN "HIGHER SALARY" 
WHEN SAL BETWEEN 1250 AND 3000 THEN "AVERAGE SALARY"
ELSE "LOW SALARY"
END AS "SALARY CHATAGORY"
FROM EMP_TABLE;


-- JOINS 
-- 1. CROSS JOINS 

SELECT * FROM EMP_TABLE
 CROSS JOIN DEPT ON 
 EMP_TABLE.DEPTNO=DEPT.DEPTNO;
 
 -- 2. INNER JOIN 
 SELECT EMP_TABLE.ENAME,EMP_TABLE.DEPTNO, DEPT.DNAME, EMP_TABLE.SAL FROM EMP_TABLE 
 INNER JOIN DEPT ON 
 DEPT.DEPTNO=EMP_TABLE.DEPTNO;
 
 -- 3. LEFT JOIN 
 SELECT * FROM EMP_TABLE 
 LEFT JOIN DEPT ON
 EMP_TABLE.DEPTNO=DEPT.DEPTNO;
 
 -- 4. RIGHT JOIN
 
 SELECT * FROM EMP_TABLE 
 RIGHT JOIN DEPT ON 
 EMP_TABLE.DEPTNO=DEPT.DEPTNO;
 
 
--  WINDOW FUNCTION 
SELECT EMPNO, DEPTNO, ENAME, SAL ,
SUM(SAL) OVER (ORDER BY EMPNO) AS SUB_SALARY 
FROM EMP_TABLE;

SELECT ROW_NUMBER() OVER (ORDER BY EMPNO) AS S_NO, EMPNO,DEPTNO, SAL FROM EMP_TABLE;

SELECT RANK() OVER (ORDER BY SAL DESC), EMPNO, DEPTNO, SAL FROM EMP_TABLE;

SELECT DENSE_RANK() OVER (ORDER BY SAL DESC), EMPNO, DEPTNO, SAL FROM EMP_TABLE;

SELECT EMPNO, DEPTNO, SAL, LAG(SAL) OVER() AS LOG_SAL FROM EMP_TABLE;

SELECT EMPNO, DEPTNO, SAL, LEAD(SAL) OVER() AS LEAD_SAL FROM EMP_TABLE;
